In [1]:
import numpy as np

# Row matrix
row = np.array([[1, 2, 3]])

# Column matrix
col = np.array([[1], [2], [3]])

# Square matrix
square = np.array([[1, 2], [3, 4]])

# Zero matrix
zero = np.zeros((3, 3))

# Identity matrix
identity = np.eye(3)

# Diagonal matrix
diagonal = np.diag([10, 20, 30])

# Upper triangular
upper = np.triu([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Lower triangular
lower = np.tril([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Symmetric matrix
symmetric = np.array([[1, 2], [2, 1]])

# Skew-symmetric
skew = np.array([[0, -2], [2, 0]])


In [6]:
print("row matrix \n", row)
print("\n col matrix \n", col)
print("\n square matrix \n", square)
print("\n zero matrix \n", zero)


row matrix 
 [[1 2 3]]

 col matrix 
 [[1]
 [2]
 [3]]

 square matrix 
 [[1 2]
 [3 4]]

 zero matrix 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print("identity matrix \n", identity)
print("\n diagonal matrix \n", diagonal)
print("\n upper matrix \n", upper)
print("\n lower matrix \n", lower)

identity matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 diagonal matrix 
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]

 upper matrix 
 [[1 2 3]
 [0 5 6]
 [0 0 9]]

 lower matrix 
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


In [8]:
print("symmetric matrix \n", symmetric)
print("\n skew matrix \n", skew)

symmetric matrix 
 [[1 2]
 [2 1]]

 skew matrix 
 [[ 0 -2]
 [ 2  0]]


In [9]:
# sparse matrix - COO
from scipy.sparse import coo_matrix

data = [5, 8, 3]
rows = [0, 1, 2]
cols = [2, 1, 2]

coo = coo_matrix((data, (rows, cols)), shape=(3, 3))

print("COO matrix:\n", coo)
print("\nChuyển về dense:\n", coo.toarray())

COO matrix:
 <COOrdinate sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	5
  (1, 1)	8
  (2, 2)	3

Chuyển về dense:
 [[0 0 5]
 [0 8 0]
 [0 0 3]]


In [10]:
# sparse matrix - CSC
from scipy.sparse import csc_matrix

dense = np.array([
    [0, 0, 3],
    [4, 0, 0],
    [0, 5, 6]
])

csc = csc_matrix(dense)

print("CSC matrix:\n", csc)
print("\nData:", csc.data)
print("Row indices:", csc.indices)
print("Column pointers:", csc.indptr)

CSC matrix:
 <Compressed Sparse Column sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 3)>
  Coords	Values
  (1, 0)	4
  (2, 1)	5
  (0, 2)	3
  (2, 2)	6

Data: [4 5 3 6]
Row indices: [1 2 0 2]
Column pointers: [0 1 2 4]


In [11]:
# sparse matrix - CSR
from scipy.sparse import csr_matrix

dense = np.array([
    [0, 0, 3],
    [4, 0, 0],
    [0, 5, 6]
])

csr = csr_matrix(dense)
print("CSR matrix:\n", csr)
print("\nData:", csr.data)
print("Indices (cột):", csr.indices)
print("Index Pointer (indptr):", csr.indptr)

CSR matrix:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	3
  (1, 0)	4
  (2, 1)	5
  (2, 2)	6

Data: [3 4 5 6]
Indices (cột): [2 0 1 2]
Index Pointer (indptr): [0 1 2 4]
