In [2]:
import numpy as np

# Matrix 2x3
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A)
print("Shape:", A.shape)
print("Element row 2, col 3:", A[1][2])  # = 6


[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Element row 2, col 3: 6


In [3]:
# Transpose
A_T = A.T
print("A:\n", A)
print("A Transpose:\n", A_T)

A:
 [[1 2 3]
 [4 5 6]]
A Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [7]:
A = np.array([[4, 2], [3, 1]])
det_A = np.linalg.det(A)
print("Det(A):", det_A) 

Det(A): -2.0


In [4]:
# Inverse
A = np.array([[4, 7],
              [2, 6]])

A_inv = np.linalg.inv(A)

print("A:\n", A)
print("A^-1:\n", A_inv)
print("A * A^-1:\n", np.dot(A, A_inv))  # ≈ identity


A:
 [[4 7]
 [2 6]]
A^-1:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A^-1:
 [[1. 0.]
 [0. 1.]]


In [5]:
# Add, Sub, Mul
B = np.array([[1, 2],
              [3, 4]])

C = np.array([[5, 6],
              [7, 8]])

print("B + C =\n", B + C)
print("B - C =\n", B - C)
D = np.dot(B, C) 
print("B x C =\n", D)


B + C =
 [[ 6  8]
 [10 12]]
B - C =
 [[-4 -4]
 [-4 -4]]
B x C =
 [[19 22]
 [43 50]]


In [6]:
# Hadamard Mul
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

hadamard = A * B 
print("Hadamard product:\n", hadamard)

Hadamard product:
 [[ 5 12]
 [21 32]]
